name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_function_js:
    name: Linting JavaScript Function 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          cd functions/sample/nodejs
          npm install

      - name: Code Linting
        run: |
          cd functions/sample/nodejs
          npm run lint

  lint_function_python:
    name: Linting Python Function 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python Dependencies
        run: |
          cd functions/sample/python
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt

      - name: Code Linting
        run: |
          cd functions/sample/python
          pylint your_app_directory/*.py  # Adjust the path to your Django app

  lint_django_server:
    name: Linting Django Server 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python Dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt

      - name: Code Linting
        run: |
          cd server
          pylint your_django_project/*.py  # Adjust the path to your Django project
